/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_lib_GameBilling */
#include "MyPurchase.h"
#ifndef _Included_org_cocos2dx_lib_GameBilling
#define _Included_org_cocos2dx_lib_GameBilling
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_lib_GameBilling
 * Method:    onPurchase
 * Signature: (I)V
 */
	JNIEXPORT void JNICALL Java_org_cocos2dx_lib_GameBilling_onPurchase
		(JNIEnv *, jobject, jint ret)
	{
		MyPurchase::sharedPurchase()->onPayResult(ret);
	}

#ifdef __cplusplus
}
#endif
#endif
